### ISSUE TITLE
Add tests for account.get & account.profile.get when not signed in

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-account#13]
If user is not signed in, `account.get()` should return undefined. So should `account.profile.get()`. I _think_ this is already the case, but we don’t have a test for that yet.

Tests need to be added to https://github.com/hoodiehq/hoodie-client-account/blob/master/tests/specs/get.js & https://github.com/hoodiehq/hoodie-client-account/blob/master/tests/specs/get-profile.js. Pass in `{}` as state, instead of the `state` variable, and make sure the `get` methods return `undefined`

**Comment by ianstalter123** [comment]
I'll work on this one thx

**Comment by gr2m** [comment]
fixed via #16
