### ISSUE TITLE
Implement account.validate() method

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-account#14]
The idea is that by default, `account.validate()` always resolves. A custom validation method can be passed as `options.validate` to the `Account` constructor.

**Comment by HipsterBrown** [comment]
`validate` is currently set to the internal state of `Account` ([Reference](https://github.com/hoodiehq/hoodie-client-account/blob/master/index.js#L16)). 

It needs to be exposed to the public API through the returned object in the constructor, https://github.com/hoodiehq/hoodie-client-account/blob/master/index.js#L21-L33 .
