### ISSUE TITLE
account.fetch() fails if not signed in

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-account#18]
We assume that `state.session` is an object here: https://github.com/hoodiehq/hoodie-client-account/blob/master/lib/fetch.js#L14

But when signed out, `state.session` is undefined

**Comment by ianstalter123** [comment]
Trying to understand how sessions work after logout here -- does get-session.js , need to be called or something similar in fetch.js?

**Comment by gr2m** [comment]
in `account.signOut`, we clear the session here: https://github.com/hoodiehq/hoodie-client-account/blob/master/lib/signout.js#L20, which removes `state.session` so it becomes undefined here: https://github.com/hoodiehq/hoodie-client-account/blob/master/helpers/clear-session.js#L7

In fetch.js, we always assume that `state.session` is an object here: https://github.com/hoodiehq/hoodie-client-account/blob/master/lib/fetch.js#L14, but after signout, it’s not an object, but `undefined`

Makes sense?

So we don’t even need to send a request if `state.session` is undefined, and can instead fail with `UnauthenticatedError` as described here: https://github.com/hoodiehq/hoodie-client-account#accountfetch

We don’t have a way to handle the errors yet, so for now you can do this:

```js
var error = new Error('Not signed in')
error.name = 'UnauthenticatedError'
throw error
```

I hope that’s not too confusing. Let me know if you have any farther questions. But also don’t worry too much, I'd suggest start a pull request, and we continue discussion there?

**Comment by ianstalter123** [comment]
Thanks for the explanation! So if I understand this issue should involve the error related calling fetch() when not authenticated.

**Comment by gr2m** [comment]
yes

**Comment by gr2m** [comment]
@ianstalter123 are you working on this one?

**Comment by ianstalter123** [comment]
Hey yes will try to do by tonight / send a pull request

**Comment by ianstalter123** [comment]
@gr2m 
You want the error checking to be added to https://github.com/hoodiehq/hoodie-client-account/blob/master/lib/fetch.js#L14 right?

**Comment by gr2m** [comment]
Yeah I’d suggest even before the `internals.fetchProperties` call, check if `state.session` is set. And if it’s not, return a rejected Promise, similar to what we do here maybe? https://github.com/hoodiehq/hoodie-client-account/blob/master/lib/sign-in.js#L14

**Comment by ianstalter123** [comment]
pull request sent

2015-12-11 13:00 GMT-08:00 Gregor Martynus <notifications@github.com>:

**Comment by gr2m** [comment]
done via e577566 & 4cb4e8c :ok_hand:
