### ISSUE TITLE
semantic-release fails to create tags / releases / changelog

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-account#49]
https://travis-ci.org/hoodiehq/hoodie-client-account#L833 @boennemann

**Comment by gr2m** [comment]
ping @boennemann. Could you have a quick look? If it’s not obvious we can look into it later

**Comment by boennemann** [comment]
Not sure if this is still relevant? Unfortunately the link doesn't point to a specific build.

**Comment by gr2m** [comment]
yes, last git release is 1.9.1:
https://github.com/hoodiehq/hoodie-client-account/releases

last npm version is 2.2.0

```
$ npm info hoodie-client-account version
2.2.0
```

Something is funky, I don’t know what it is, could you have a look?

**Comment by gr2m** [comment]
works again :v:
