### ISSUE TITLE
account.signOut() does not resolve with account properties

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-account#50]
This is what we want

```js
// given user is signed in as "pat"
account.signOut()

.then(function (properties) {
  properties.username // should be "pat"
})
```

---

- [x] claim this issue (@mxstbr)
- [x] start a pull request (https://github.com/hoodiehq/hoodie-client-account/pull/51)
- [ ] [uncomment failing test](https://github.com/hoodiehq/hoodie-client-account/blob/042b024308ced5a330d6c67e81693744e4aa732d/test/integration/sign-in-test.js#L62-L63) and set `t.plan(10)` to `t.plan(11)`. Test should fail now
- [ ] fix the issue 
- [ ] review & merge
- [ ] update https://github.com/gr2m/milestones/issues/88
- [ ] uncomment [test in Something Tracker App](https://github.com/hoodiehq/hoodie-app-something-tracker/blob/c91edbe5437fa768663c77f94aebac255e59714d/test/walkthrough-test.js#L80)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions

**Comment by mxstbr** [comment]
Would love to take a crack at this!

**Comment by gr2m** [comment]
All yours :+1:
