### ISSUE TITLE
implement account.update()

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-account#52]
Only `username` and `password` can be changed at this point, and only the valid session is required for authorization at this point.

---

- [x] claim this issue (@finnp)
- [x] update the [README](https://github.com/hoodiehq/hoodie-client-account#api): add `account.update` (it is similar to [account.profile.update](https://github.com/hoodiehq/hoodie-client-account#accountprofileupdate) for now)
- [x] add unit & integration test. In the latter, make sure `account.username` is set to the new username if it got changed, and sign out & back in with the new username / password
- [x] implement account.update()
- [x] review & merge
- [ ] update https://github.com/gr2m/milestones/issues/88
- [ ] [uncomment integration test](https://github.com/hoodiehq/hoodie-app-something-tracker/blob/6c8b0f5a8aecb8fd3645bbb23782f6d3effd66af/test/account-test.js#L112-L136) if https://github.com/hoodiehq/hoodie-server-account/issues/53 is done

**Comment by finnp** [comment]
I'm going to have a look at this.

**Comment by gr2m** [comment]
nice, all yours :+1:

**Comment by gr2m** [comment]
done via 63
