### ISSUE TITLE
hoodie.account.fetch(), .update(), .profile.fetch() and .profile.update() should fail with UnauthenticatedError if session is invalid, but currently fails with "Not FoundError"

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-account#54]
To simulate an unauthenticated state, replace `session.id` in `localStorage.account` with a bogus value, then reload the page and do `account.fetch()`

---

- [x] claim this issue (@realtin)
- [x] start a PR (#62)
- [x] add unit and integration tests for `account.fetch()`. In the latter, make sure that an "unauthenticate" event gets triggered
- [ ] fix account.fetch()
- [ ] repeat steps for `account.update`, `account.profile.fetch` and `account.profile.update`
- [ ] review & merge
- [ ] update https://github.com/gr2m/milestones/issues/88

**Comment by Realtin** [comment]
I'll try this one!

**Comment by gr2m** [comment]
this is on hold as it will probably be fixed by https://github.com/hoodiehq/hoodie-client-account/issues/64
