### ISSUE TITLE
README: add link account.isSignedIn to API list

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-account#55]
[account.isSignedIn](https://github.com/hoodiehq/hoodie-client-account#accountissignedin) is document, but not listed in https://github.com/hoodiehq/hoodie-client-account#api

---

- [x] claim this issue (comment below or assign yourself)
- [x] start a PR
- [x] add the link to the README
- [x] review & merge
- [ ] update https://github.com/gr2m/milestones/issues/88

**Comment by Charlotteis** [comment]
I did this one, hope you don't mind. #58

**Comment by gr2m** [comment]
Not at all :) Let me know if you want to take on any of the other issues, happy to coach you if you like

**Comment by Charlotteis** [comment]
Thanks! I need to take a look at the starter issues one day soon :)
