### ISSUE TITLE
Implement account.hasInvalidSession()

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-account#56]
If a session gets invalidated, "unauthenticate" events get triggered, for example when `account.fetch()` is called. Once unauthenticated, `account.isUnauthenticated` shall return true, otherwise false. The unauthenticate state shall also be persisted in localStorage.

`account.signIn` with the same username creates a new valid session and emits the `reauthenticate` event

---

- [x] claim this issue (comment below or assign yourself) (@toh82)
- [x] start a PR (#72)
- [x] add unit tests for `account.hasInvalidSession()`
- [x] implement `account.hasInvalidSession()`, and persist the unauthenticate state in localStorage
- [ ] update [README](https://github.com/hoodiehq/hoodie-client-account) (add `account.hasInvalidSession` and remove issue reference in Events)
- [ ] review & merge
- [ ] update https://github.com/gr2m/milestones/issues/88

**Comment by Guria** [comment]
> Once unauthenticated, account.isUnauthenticated shall return false, otherwise true.

Shouldn't it be vice versa?

**Comment by gr2m** [comment]
yessir :+1: fixed it in the issue description. Thanks @Guria
