### ISSUE TITLE
account.signIn() to emit `reauthenticate` event when unauthenticated

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-account#57]
depends on #56

If `account.isUnauthenticated()` returns `true` and the user signs in with the same username, then an `reauthenticate` event should be triggered (instead of `signin`)

---

- [x] claim this issue (@espy)
- [x] start a PR (#60)
- [x] add unit and integration tests. Integration tests can be added [here](https://github.com/hoodiehq/hoodie-client-account/blob/master/test/integration/events-test.js)
- [x] implement the reauthenticate event
- [x] update [README](https://github.com/hoodiehq/hoodie-client-account#events)
- [ ] review & merge
- [ ] update https://github.com/gr2m/milestones/issues/88

**Comment by espy** [comment]
PR is ready for review!

**Comment by espy** [comment]
That was very cool :)
