### ISSUE TITLE
getState does not set a fallback url 

### ISSUE THREAD

**Issue by Realtin** [hoodiehq/hoodie-client-account#61]
When reproducing the Error from #54 a GET Request to `http://127.0.0.1:8080/undefined/session/account` is send. 

setting an empty String as a fallback in utils/get-state.js  should fix that.

**Comment by gr2m** [comment]
it’s using `state.baseUrl` in fetch.js and profile-fetch.js, but we never set that. It should use `state.url` instead

**Comment by gr2m** [comment]
@Realtin do you want to fix it? If not I can make a stater issue for others out of this :)

**Comment by Realtin** [comment]
I started with this but since I'm a bit busy right now you can just make it a starter issue and if nobody wants it then I'll try again :)

**Comment by gr2m** [comment]
perfect :+1:

**Comment by toh82** [comment]
closing in favor of #64
