### ISSUE TITLE
use `state.url` instead of `state.baseUrl` in fetch.js and profile-fetch.js

### ISSUE THREAD

**Issue by toh82** [hoodiehq/hoodie-client-account#64]
Reported in: https://github.com/hoodiehq/hoodie-client-account/issues/61#
When reproducing the Error from #54 a GET Request to `http://127.0.0.1:8080/undefined/session/account` is send. 

Fix that by using `state.url` instead of `state.baseUrl` 

-------
- [x] claim this issue (@Endi1)
- [x] start a PR
- [x] uncomment integration test `test/integration/fetch-url-test.js`
- [x] fix `state.baseUrl` in fetch.js
- [x] fix `state.baseUrl` in profile-fetch.js
- [x] search for more appearance of `state.baseUrl`
- [x] run tests and make sure that all are green
- [ ] review & merge
- [ ] check if https://github.com/hoodiehq/hoodie-client-account/pull/62 is resolved

**Comment by Charlotteis** [comment]
Ohai @toh82 thanks so much for this great issue!

**Comment by Endi1** [comment]
Can I give this a try?

**Comment by gr2m** [comment]
@Endi1 sure. @toh82 wanted to prepare the integration test tomorrow, but if you feel confident you can go ahead :)

**Comment by Endi1** [comment]
Thanks, I'll submit a PR by tomorrow :)

**Comment by toh82** [comment]
Hey @Endi1 great that you took this issue, do you need any Information on this topic?
If I should prepare the tests for you, let me know.

**Comment by Endi1** [comment]
Hey @toh82 I'll try to write the tests too, but if I get stuck I'll be sure to ask you. Thanks!

**Comment by Endi1** [comment]
@toh82 I have been slamming my head against the wall the whole afternoon and I can't seem to get this to work. Maybe if you prepare the tests then I'll have a better chance :)

**Comment by gr2m** [comment]
@Endi1oh no, so sorry to hear that! Hang in there, we’ll help you get trough this :)

**Comment by gr2m** [comment]
@toh82 can you prepare the tests for Endi? You can send them in a separate PR, comment them out with a reference to this issue in a comment

**Comment by toh82** [comment]
@gr2m @Endi1 I'm currently on #56 and my time this week is hardly limited :( 
sorry about that, I guess I can start to work on this tests at Friday evening.

**Comment by Endi1** [comment]
@toh82 sounds good :)

**Comment by gr2m** [comment]
Thanks Tobias!

**Comment by toh82** [comment]
Hello @Endi1 i started a the PR and added branch `issue-64-use-stateurl` 
you can see the test in the referenced PR no worries that the test currently fails, it has to since the `baseUrl` isn't fixed. 

If you have further questions let me know.

**Comment by toh82** [comment]
@Endi1 Sorry for the delay, task should now be ready, if you have questions don't hesitate asking me or @gr2m

**Comment by gr2m** [comment]
@Endi1 do you still want to give this a go? We are getting to a point where this becomes a blogger, if you could finish this by Monday, that’d be ace. If you have no time, no problem at all, I’m sure someone else would like to pick it up

**Comment by toh82** [comment]
this will be done with pr #72
