### ISSUE TITLE
README: example for account.profile.fetch() has a bug

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-account#79]
follow up for https://github.com/hoodiehq/hoodie-client-account/pull/78#discussion_r54120950

```js
account.fetch('fullname').then(function (createdAt) {
  alert('Hey there ' + fullname)
})
```

should be 

```js
account.fetch('fullname').then(function (fullname) {
  alert('Hey there ' + fullname)
})
```

Please help free to turn this into a [starter issue](http://hood.ie/blog/starter-issues.html) <3 Edit my issue description directly, or create a follow up issue so we can close this one :)

**Comment by HipsterBrown** [comment]
Closed by https://github.com/hoodiehq/hoodie-client-account/pull/81
